// Date: 30/06/2014 16:44:00
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.roller.roller.models.mottbro;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTrackStraight extends ModelBase
{
  //fields
    ModelRenderer Main_Beam;
    ModelRenderer Track1;
    ModelRenderer Track2;
    ModelRenderer Track3;
    ModelRenderer Track4;
    ModelRenderer Track5;
    ModelRenderer Track6;
    ModelRenderer Track7;
    ModelRenderer Track8;
    ModelRenderer Track9;
    ModelRenderer Track10;
    ModelRenderer Track11;
    ModelRenderer Track12;
    ModelRenderer Track13;
    ModelRenderer Track14;
    ModelRenderer Track15;
    ModelRenderer Track16;
    ModelRenderer Beam1;
    ModelRenderer Beam2;
    ModelRenderer Beam3;
    ModelRenderer Beam4;
    ModelRenderer Beam5;
    ModelRenderer Cross1;
    ModelRenderer Beam6;
    ModelRenderer Cross2;
    ModelRenderer Cross3;
    ModelRenderer Cross4;
  
  public ModelTrackStraight()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Main_Beam = new ModelRenderer(this, 23, 12);
      Main_Beam.addBox(-2F, -1F, 0F, 4, 3, 16);
      Main_Beam.setRotationPoint(0F, 16F, -8F);
      Main_Beam.setTextureSize(64, 32);
      Main_Beam.mirror = true;
      setRotation(Main_Beam, 0F, 0F, 0F);
      Track1 = new ModelRenderer(this, 0, 0);
      Track1.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track1.setRotationPoint(8.7F, 9.7F, -8F);
      Track1.setTextureSize(64, 32);
      Track1.mirror = true;
      setRotation(Track1, 0F, 0F, 0F);
      Track2 = new ModelRenderer(this, 0, 0);
      Track2.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track2.setRotationPoint(-6.3F, 11.1F, -8F);
      Track2.setTextureSize(64, 32);
      Track2.mirror = true;
      setRotation(Track2, 0F, 0F, 0.7853982F);
      Track3 = new ModelRenderer(this, 0, 0);
      Track3.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track3.setRotationPoint(8F, 10.4F, -8F);
      Track3.setTextureSize(64, 32);
      Track3.mirror = true;
      setRotation(Track3, 0F, 0F, 0F);
      Track4 = new ModelRenderer(this, 0, 0);
      Track4.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track4.setRotationPoint(-5.3F, 11.1F, -8F);
      Track4.setTextureSize(64, 32);
      Track4.mirror = true;
      setRotation(Track4, 0F, 0F, 0.7853982F);
      Track5 = new ModelRenderer(this, 0, 0);
      Track5.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track5.setRotationPoint(-4.3F, 9.7F, -8F);
      Track5.setTextureSize(64, 32);
      Track5.mirror = true;
      setRotation(Track5, 0F, 0F, 0F);
      Track6 = new ModelRenderer(this, 0, 0);
      Track6.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track6.setRotationPoint(-6.3F, 10.1F, -8F);
      Track6.setTextureSize(64, 32);
      Track6.mirror = true;
      setRotation(Track6, 0F, 0F, 0.7853982F);
      Track7 = new ModelRenderer(this, 0, 0);
      Track7.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track7.setRotationPoint(-5.3F, 10.1F, -8F);
      Track7.setTextureSize(64, 32);
      Track7.mirror = true;
      setRotation(Track7, 0F, 0F, 0.7853982F);
      Track8 = new ModelRenderer(this, 0, 0);
      Track8.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track8.setRotationPoint(8F, 9F, -8F);
      Track8.setTextureSize(64, 32);
      Track8.mirror = true;
      setRotation(Track8, 0F, 0F, 0F);
      Track9 = new ModelRenderer(this, 0, 0);
      Track9.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track9.setRotationPoint(-5F, 9F, -8F);
      Track9.setTextureSize(64, 32);
      Track9.mirror = true;
      setRotation(Track9, 0F, 0F, 0F);
      Track10 = new ModelRenderer(this, 0, 0);
      Track10.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track10.setRotationPoint(7.7F, 11.1F, -8F);
      Track10.setTextureSize(64, 32);
      Track10.mirror = true;
      setRotation(Track10, 0F, 0F, 0.7853982F);
      Track11 = new ModelRenderer(this, 0, 0);
      Track11.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track11.setRotationPoint(-5F, 10.4F, -8F);
      Track11.setTextureSize(64, 32);
      Track11.mirror = true;
      setRotation(Track11, 0F, 0F, 0F);
      Track12 = new ModelRenderer(this, 0, 0);
      Track12.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track12.setRotationPoint(6.7F, 10.1F, -8F);
      Track12.setTextureSize(64, 32);
      Track12.mirror = true;
      setRotation(Track12, 0F, 0F, 0.7853982F);
      Track13 = new ModelRenderer(this, 0, 0);
      Track13.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track13.setRotationPoint(7.7F, 10.1F, -8F);
      Track13.setTextureSize(64, 32);
      Track13.mirror = true;
      setRotation(Track13, 0F, 0F, 0.7853982F);
      Track14 = new ModelRenderer(this, 0, 0);
      Track14.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track14.setRotationPoint(-5.7F, 9.7F, -8F);
      Track14.setTextureSize(64, 32);
      Track14.mirror = true;
      setRotation(Track14, 0F, 0F, 0F);
      Track15 = new ModelRenderer(this, 0, 0);
      Track15.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track15.setRotationPoint(6.7F, 11.1F, -8F);
      Track15.setTextureSize(64, 32);
      Track15.mirror = true;
      setRotation(Track15, 0F, 0F, 0.7853982F);
      Track16 = new ModelRenderer(this, 0, 0);
      Track16.addBox(-2F, -1F, 0F, 1, 1, 16);
      Track16.setRotationPoint(7.3F, 9.7F, -8F);
      Track16.setTextureSize(64, 32);
      Track16.mirror = true;
      setRotation(Track16, 0F, 0F, 0F);
      Beam1 = new ModelRenderer(this, 5, 21);
      Beam1.addBox(-2F, -1F, 0F, 1, 9, 2);
      Beam1.setRotationPoint(6.9F, 10.9F, -1F);
      Beam1.setTextureSize(64, 32);
      Beam1.mirror = true;
      setRotation(Beam1, 0F, 0F, 0.6108652F);
      Beam2 = new ModelRenderer(this, 5, 21);
      Beam2.addBox(-2F, -1F, 0F, 1, 9, 2);
      Beam2.setRotationPoint(-4.1F, 9.8F, -1F);
      Beam2.setTextureSize(64, 32);
      Beam2.mirror = true;
      setRotation(Beam2, 0F, 0F, -0.6108652F);
      Beam3 = new ModelRenderer(this, 12, 22);
      Beam3.addBox(-2F, -1F, 0F, 1, 9, 1);
      Beam3.setRotationPoint(6.9F, 10.9F, 7F);
      Beam3.setTextureSize(64, 32);
      Beam3.mirror = true;
      setRotation(Beam3, 0F, 0F, 0.6108652F);
      Beam4 = new ModelRenderer(this, 12, 22);
      Beam4.addBox(-2F, -1F, 0F, 1, 9, 1);
      Beam4.setRotationPoint(6.9F, 10.9F, -8F);
      Beam4.setTextureSize(64, 32);
      Beam4.mirror = true;
      setRotation(Beam4, 0F, 0F, 0.6108652F);
      Beam5 = new ModelRenderer(this, 0, 22);
      Beam5.addBox(-2F, -1F, 0F, 1, 9, 1);
      Beam5.setRotationPoint(-4.1F, 9.8F, -8F);
      Beam5.setTextureSize(64, 32);
      Beam5.mirror = true;
      setRotation(Beam5, 0F, 0F, -0.6108652F);
      Cross1 = new ModelRenderer(this, 0, 22);
      Cross1.addBox(-2F, -1F, 0F, 1, 9, 1);
      Cross1.setRotationPoint(3.5F, 13F, -8F);
      Cross1.setTextureSize(64, 32);
      Cross1.mirror = true;
      setRotation(Cross1, 0F, 0F, 1.570796F);
      Beam6 = new ModelRenderer(this, 0, 22);
      Beam6.addBox(-2F, -1F, 0F, 1, 9, 1);
      Beam6.setRotationPoint(-4.1F, 9.8F, 7F);
      Beam6.setTextureSize(64, 32);
      Beam6.mirror = true;
      setRotation(Beam6, 0F, 0F, -0.6108652F);
      Cross2 = new ModelRenderer(this, 0, 22);
      Cross2.addBox(-2F, -1F, 0F, 1, 9, 1);
      Cross2.setRotationPoint(3.5F, 13F, 0F);
      Cross2.setTextureSize(64, 32);
      Cross2.mirror = true;
      setRotation(Cross2, 0F, 0F, 1.570796F);
      Cross3 = new ModelRenderer(this, 0, 22);
      Cross3.addBox(-2F, -1F, 0F, 1, 9, 1);
      Cross3.setRotationPoint(3.5F, 13F, -1F);
      Cross3.setTextureSize(64, 32);
      Cross3.mirror = true;
      setRotation(Cross3, 0F, 0F, 1.570796F);
      Cross4 = new ModelRenderer(this, 0, 22);
      Cross4.addBox(-2F, -1F, 0F, 1, 9, 1);
      Cross4.setRotationPoint(3.5F, 13F, 7F);
      Cross4.setTextureSize(64, 32);
      Cross4.mirror = true;
      setRotation(Cross4, 0F, 0F, 1.570796F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Main_Beam.render(f5);
    Track1.render(f5);
    Track2.render(f5);
    Track3.render(f5);
    Track4.render(f5);
    Track5.render(f5);
    Track6.render(f5);
    Track7.render(f5);
    Track8.render(f5);
    Track9.render(f5);
    Track10.render(f5);
    Track11.render(f5);
    Track12.render(f5);
    Track13.render(f5);
    Track14.render(f5);
    Track15.render(f5);
    Track16.render(f5);
    Beam1.render(f5);
    Beam2.render(f5);
    Beam3.render(f5);
    Beam4.render(f5);
    Beam5.render(f5);
    Cross1.render(f5);
    Beam6.render(f5);
    Cross2.render(f5);
    Cross3.render(f5);
    Cross4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
