// Date: 24.07.2014 00:11:42
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.roller.roller.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTrack45 extends ModelBase
{
  //fields
    ModelRenderer aussen;
    ModelRenderer aussen2;
    ModelRenderer mitte;
    ModelRenderer Shape3;
    ModelRenderer Shape31;
    ModelRenderer Shape32;
    ModelRenderer Shape33;
  
  public ModelTrack45()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      aussen = new ModelRenderer(this, 0, 0);
      aussen.addBox(0F, 0F, 0F, 2, 24, 2);
      aussen.setRotationPoint(5F, 7.4F, -9.4F);
      aussen.setTextureSize(128, 64);
      aussen.mirror = true;
      setRotation(aussen, 0.7853982F, 0F, 0F);
      aussen2 = new ModelRenderer(this, 0, 0);
      aussen2.addBox(0F, 0F, 0F, 2, 24, 2);
      aussen2.setRotationPoint(-7F, 7.4F, -9.4F);
      aussen2.setTextureSize(128, 64);
      aussen2.mirror = true;
      setRotation(aussen2, 0.7853982F, 0F, 0F);
      mitte = new ModelRenderer(this, 11, 0);
      mitte.addBox(0F, 0F, 0F, 4, 23, 1);
      mitte.setRotationPoint(-2F, 7.666667F, -8.8F);
      mitte.setTextureSize(128, 64);
      mitte.mirror = true;
      setRotation(mitte, 0.7853982F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 25, 0);
      Shape3.addBox(0F, 0F, 0F, 4, 1, 1);
      Shape3.setRotationPoint(-5.7F, 10.7F, -4.4F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, -0.8563749F, 0F, 0F);
      Shape31 = new ModelRenderer(this, 25, 0);
      Shape31.addBox(0F, 0F, 0F, 4, 1, 1);
      Shape31.setRotationPoint(1.9F, 11.2F, -5.133333F);
      Shape31.setTextureSize(128, 64);
      Shape31.mirror = true;
      setRotation(Shape31, 0.6795149F, -0.1058833F, -0.077958F);
      Shape32 = new ModelRenderer(this, 25, 0);
      Shape32.addBox(0F, 0F, 0F, 4, 1, 1);
      Shape32.setRotationPoint(1.9F, 19F, 2.6F);
      Shape32.setTextureSize(128, 64);
      Shape32.mirror = true;
      setRotation(Shape32, 0.6795149F, -0.1058833F, -0.077958F);
      Shape33 = new ModelRenderer(this, 25, 0);
      Shape33.addBox(0F, 0F, 0F, 4, 1, 1);
      Shape33.setRotationPoint(-5.7F, 18.6F, 3.4F);
      Shape33.setTextureSize(128, 64);
      Shape33.mirror = true;
      setRotation(Shape33, -0.8563749F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    aussen.render(f5);
    aussen2.render(f5);
    mitte.render(f5);
    Shape3.render(f5);
    Shape31.render(f5);
    Shape32.render(f5);
    Shape33.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
