// Date: 27.03.2015 20:19:31
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.roller.roller.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPitchedCurve extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape21;
    ModelRenderer Shape3;
    ModelRenderer Shape31;
    ModelRenderer Shape4;
  
  public ModelPitchedCurve()
  {
    textureWidth = 64;
    textureHeight = 16;
    
      Shape1 = new ModelRenderer(this, 0, 9);
      Shape1.addBox(-6F, 0F, 0F, 12, 2, 2);
      Shape1.setRotationPoint(-5.3F, 22F, -5.3F);
      Shape1.setTextureSize(64, 16);
      Shape1.mirror = true;
      setRotation(Shape1, -0.4712389F, 0.7853982F, 0F);
      Shape2 = new ModelRenderer(this, 0, 4);
      Shape2.addBox(-9F, 0F, 0F, 18, 4, 1);
      Shape2.setRotationPoint(-3F, 14.5F, -3F);
      Shape2.setTextureSize(64, 16);
      Shape2.mirror = true;
      setRotation(Shape2, -0.3717861F, 0.7853982F, 0F);
      Shape21 = new ModelRenderer(this, 0, 0);
      Shape21.addBox(-11F, 0F, 0F, 22, 2, 2);
      Shape21.setRotationPoint(-2F, 8F, -2F);
      Shape21.setTextureSize(64, 16);
      Shape21.mirror = true;
      setRotation(Shape21, -0.4712389F, 0.7853982F, 0F);
      Shape3 = new ModelRenderer(this, 38, 4);
      Shape3.addBox(-9F, 0F, 0F, 1, 5, 1);
      Shape3.setRotationPoint(0F, 10F, -5F);
      Shape3.setTextureSize(64, 16);
      Shape3.mirror = true;
      setRotation(Shape3, -0.1487144F, 0.7853982F, 0F);
      Shape31 = new ModelRenderer(this, 38, 4);
      Shape31.addBox(1F, 0F, 0F, 1, 5, 1);
      Shape31.setRotationPoint(0F, 10F, -5F);
      Shape31.setTextureSize(64, 16);
      Shape31.mirror = true;
      setRotation(Shape31, -0.1487144F, 0.7853982F, 0F);
      Shape4 = new ModelRenderer(this, 38, 4);
      Shape4.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape4.setRotationPoint(-4.5F, 18F, -3.5F);
      Shape4.setTextureSize(64, 16);
      Shape4.mirror = true;
      setRotation(Shape4, -0.3717861F, 0.7853982F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity );
    Shape1.render(f5);
    Shape2.render(f5);
    Shape21.render(f5);
    Shape3.render(f5);
    Shape31.render(f5);
    Shape4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
