// Date: 06.03.2015 17:37:26
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.roller.roller.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTrackQuer2 extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape2;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
  
  public ModelTrackQuer2()
  {
    textureWidth = 64;
    textureHeight = 16;
    
      Shape1 = new ModelRenderer(this, 4, 0);
      Shape1.addBox(0F, 0F, 0F, 15, 1, 4);
      Shape1.setRotationPoint(-2.5F, 23F, 8F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0.7853982F, 0F);
      Shape12 = new ModelRenderer(this, 0, 5);
      Shape12.addBox(0F, 0F, 0F, 22, 2, 2);
      Shape12.setRotationPoint(-7F, 22F, 8F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0.8028515F, 0F);
      Shape13 = new ModelRenderer(this, 42, 0);
      Shape13.addBox(0F, 0F, 0F, 4, 2, 2);
      Shape13.setRotationPoint(5F, 22F, 8F);
      Shape13.setTextureSize(64, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0.7853982F, 0F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape2.setRotationPoint(5.5F, 23F, -3F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 1.226894F, -0.027884F, 0F);
      Shape21 = new ModelRenderer(this, 0, 0);
      Shape21.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape21.setRotationPoint(-3.5F, 23F, 7F);
      Shape21.setTextureSize(64, 32);
      Shape21.mirror = true;
      setRotation(Shape21, 1.226897F, 1.570796F, 0F);
      Shape22 = new ModelRenderer(this, 0, 0);
      Shape22.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape22.setRotationPoint(7F, 23F, 6.5F);
      Shape22.setTextureSize(64, 32);
      Shape22.mirror = true;
      setRotation(Shape22, 1.226894F, -2.356194F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape2.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
