// Date: 08.03.2015 11:13:16
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.roller.roller.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class tmp extends ModelBase
{
  //fields
    ModelRenderer Shape2;
    public ModelRenderer speed;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
    ModelRenderer Shape1;
    ModelRenderer Shape12;
    public ModelRenderer[] brake = new ModelRenderer[4];
    public ModelRenderer[] start = new ModelRenderer[2];
  
  public tmp()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shape2 = new ModelRenderer(this, 32, 0);
      Shape2.addBox(0F, 0F, 0F, 1, 2, 10);
      Shape2.setRotationPoint(3F, 21.5F, -5F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      speed = new ModelRenderer(this, 44, 0);
      speed.addBox(0F, 0F, 0F, 2, 2, 8);
      speed.setRotationPoint(-1F, 22F, -4F);
      speed.setTextureSize(64, 32);
      speed.mirror = true;
      setRotation(speed, 0F, 0F, 0F);
      Shape22 = new ModelRenderer(this, 32, 0);
      Shape22.addBox(0F, 0F, 0F, 1, 1, 10);
      Shape22.setRotationPoint(4F, 22.5F, -5F);
      Shape22.setTextureSize(64, 32);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
      Shape23 = new ModelRenderer(this, 32, 0);
      Shape23.addBox(0F, 0F, 0F, 1, 2, 10);
      Shape23.setRotationPoint(-4F, 21.5F, -5F);
      Shape23.setTextureSize(64, 32);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, 0F);
      Shape24 = new ModelRenderer(this, 32, 0);
      Shape24.addBox(0F, 0F, 0F, 1, 1, 10);
      Shape24.setRotationPoint(-5F, 22.5F, -5F);
      Shape24.setTextureSize(64, 32);
      Shape24.mirror = true;
      setRotation(Shape24, 0F, 0F, 0F);
      
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 1, 5, 16);
      Shape1.setRotationPoint(7F, 19F, -8F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 0, 0);
      Shape12.addBox(0F, 0F, 0F, 1, 5, 16);
      Shape12.setRotationPoint(-8F, 19F, -8F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      brake[0] = Shape2;
      brake[1] = Shape22;
      brake[2] = Shape23;
      brake[3] = Shape24;
      start[0] = Shape1;
      start[1] = Shape12;
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape2.render(f5);
    speed.render(f5);
    Shape22.render(f5);
    Shape23.render(f5);
    Shape24.render(f5);
    Shape1.render(f5);
    Shape12.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,  e);
  }

}
